2023-12-11 08:58:22,632 - INFO - 
Config:
'add_train': False
'batch_size': 64
'continue_flag': ''
'cur_time': '2023_12_11_08_58_06'
'debug_mode': False
'debug_num': 500
'do_continue_train': False
'do_figure_save': False
'do_log_print_to_screen': True
'do_log_save_to_file': True
'do_predict': True
'do_train': True
'do_train_visualized': False
'dropout_rate': 0.2
'epoch': 20
'feature_columns': [2, 3, 4, 5, 6, 7, 8]
'figure_save_path': './figure/'
'hidden_size': 128
'input_size': 7
'label_columns': [4, 5]
'label_in_feature_index': [2, 3]
'learning_rate': 0.001
'log_save_path': './log/2023_12_11_08_58_06_pytorch/'
'lstm_layers': 2
'model_postfix': {'pytorch': '.pth'
'keras': '.h5'
'tensorflow': '.ckpt'}
'model_save_path': 'D:\\zcj\\myweb\\teststock\\prediction\\LSTMPredictStock\\saved_models/'
'output_size': 2
'patience': 5
'predict_day': 1
'random_seed': 42
'shuffle_train_data': True
'time_step': 20
'train_data_path': 'D:\\zcj\\myweb\\teststock\\prediction\\LSTMPredictStock\\data/py'
'train_data_rate': 0.95
'use_cuda': False
'used_frame': 'pytorch'
'valid_data_rate': 0.15
2023-12-11 08:58:24,745 - INFO - Epoch 0/20
2023-12-11 08:58:27,426 - INFO - The train loss is 0.720798. The valid loss is 0.338915.
2023-12-11 08:58:27,445 - ERROR - Run Error
Traceback (most recent call last):
  File "D:\zcj\myweb\teststock\prediction\LSTMPredictStock\pypredic.py", line 243, in main
    train(config, logger, [train_X, train_Y, valid_X, valid_Y],code)
  File "D:\zcj\myweb\teststock\prediction\LSTMPredictStock\model\model_pytorch.py", line 104, in train
    torch.save(model.state_dict(), config.model_save_path + config.model_name)  # Ä£ÐÍ±£´æ
AttributeError: 'Config' object has no attribute 'model_name'
2023-12-11 09:00:17,574 - INFO - D:\zcj\myweb\teststock\prediction\LSTMPredictStock\model\model_pytorch.py changed, reloading.
