2023-12-11 08:48:06,739 - INFO - 
Config:
'add_train': False
'batch_size': 64
'continue_flag': ''
'cur_time': '2023_12_11_08_47_51'
'debug_mode': False
'debug_num': 500
'do_continue_train': False
'do_figure_save': False
'do_log_print_to_screen': True
'do_log_save_to_file': True
'do_predict': True
'do_train': True
'do_train_visualized': False
'dropout_rate': 0.2
'epoch': 20
'feature_columns': [2, 3, 4, 5, 6, 7, 8]
'figure_save_path': './figure/'
'hidden_size': 128
'input_size': 7
'label_columns': [4, 5]
'label_in_feature_index': [2, 3]
'learning_rate': 0.001
'log_save_path': './log/2023_12_11_08_47_51_pytorch/'
'lstm_layers': 2
'model_postfix': {'pytorch': '.pth'
'keras': '.h5'
'tensorflow': '.ckpt'}
'model_save_path': './saved_models/'
'output_size': 2
'patience': 5
'predict_day': 1
'random_seed': 42
'shuffle_train_data': True
'time_step': 20
'train_data_path': './data/py'
'train_data_rate': 0.95
'use_cuda': False
'used_frame': 'pytorch'
'valid_data_rate': 0.15
2023-12-11 08:48:06,742 - ERROR - Run Error
Traceback (most recent call last):
  File "D:\zcj\myweb\teststock\prediction\LSTMPredictStock\pypredic.py", line 235, in main
    data_gainer = Data(config,code)
  File "D:\zcj\myweb\teststock\prediction\LSTMPredictStock\pypredic.py", line 93, in __init__
    self.data, self.data_column_name = self.read_data()
  File "D:\zcj\myweb\teststock\prediction\LSTMPredictStock\pypredic.py", line 110, in read_data
    init_data = pd.read_csv(self.config.train_data_path+self.code+'.csv', usecols=self.config.feature_columns)
AttributeError: 'Data' object has no attribute 'code'
2023-12-11 08:49:45,588 - INFO - D:\zcj\myweb\teststock\prediction\LSTMPredictStock\pypredic.py changed, reloading.
